# Generated by Django 3.1 on 2020-09-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20200904_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='n_sender',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_read',
            field=models.BooleanField(default=False),
        ),
    ]
